server:
  port: 8001

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: none

    show-sql: true
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5432/postgres
      username: ersalomo
      password: Ersalom0@



      server:
        port: 8081

      spring:
        datasource:
          url: jdbc:mysql://localhost:3306/netjs
          username: DB_USER
          password: DB_PASSWORD
        jpa:
          properties:
            hibernate:
              sqldialect: org.hibernate.dialect.MySQLDialect
              showsql: true